//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class WFormSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WFormSettings defaultInstance = ((WFormSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WFormSettings())));
        
        public static WFormSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWinFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainWinFormLocation"]));
            }
            set {
                this["MainWinFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainWinFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainWinFormSize"]));
            }
            set {
                this["MainWinFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Forms.FormWindowState MainWinFormLocationState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainWinFormLocationState"]));
            }
            set {
                this["MainWinFormLocationState"] = value;
            }
        }
    }
}
